In [4]:
import numpy as np
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
array = [1,2,3,4,5,6]

np.reshape(array,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
import numpy  as np

array = np.array([1.57,2.48,3.93,4.33])
print('/n배열 출력하기')
print(array)

print('/nnp.ceil() 함수는 소수 자리를 올림한다')
result = np.ceil(array)
print(result)

print('/nnp.floor(array)함수의 소수자리를 버림한다')
result = np.floor(array)
print(result)

print('/nnp.round() 함수의 소수자리를 반올림한다')
result = np.round(array)
print(result)

print('/n소수점 1자리에서 반올림')
result = np.round(array,1)
print(result)

print('/n루트 씌우기')
result = np.sqrt(array)
print(result)

arr = np.arange(10)
print(arr)
print()

print('/nexp함수 적용')
result = np.exp(arr)
print(result)

x=[5,4]
y=[6,3]

print('.maximum(x,y)')
result = np.maximum(x,y)
print(result)

print('-'*30)

array1 = np.array([1.1,2.2,3.3,4.4])
print('/n배열 출력하기1')
print(array1)

array2 = np.array([1.1,2.2,3.3,4.4])
print('/n배열 출력하기2')
print(array2)

print('/n절대값 구하기')
result = np.abs(array1)
print(result)

print('/n배열 요소들의 값 합치기')
result = np.sum(array1)
print(array1)

print('/n배열요소들의 값 비교하기')
result = np.equal(array1,array2)
print(result)

print()


/n배열 출력하기
[1.57 2.48 3.93 4.33]
/nnp.ceil() 함수는 소수 자리를 올림한다
[2. 3. 4. 5.]
/nnp.floor(array)함수의 소수자리를 버림한다
[1. 2. 3. 4.]
/nnp.round() 함수의 소수자리를 반올림한다
[2. 2. 4. 4.]
/n소수점 1자리에서 반올림
[1.6 2.5 3.9 4.3]
/n루트 씌우기
[1.25299641 1.57480157 1.98242276 2.0808652 ]
[0 1 2 3 4 5 6 7 8 9]

/nexp함수 적용
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
.maximum(x,y)
[6 4]
------------------------------
/n배열 출력하기1
[1.1 2.2 3.3 4.4]


<function print>